import type { Metadata } from "next";

import ProtectedStorefrontLayout from "@/components/layout/ProtectedStorefrontLayout";
import Providers from "../providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="antialiased">
      <Providers>
        <ProtectedStorefrontLayout>{children}</ProtectedStorefrontLayout>
      </Providers>
    </div>
  );
}
