import type { Metadata } from "next";

import ProtectedStorefrontLayout from "@/components/layout/ProtectedStorefrontLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="antialiased">
      <ProtectedStorefrontLayout includeFooter={false}>{children}</ProtectedStorefrontLayout>
    </div>
  );
}
